#!/usr/bin/env node
/**
 * Refreshes the vendored Inter subsets from Google Fonts.
 *
 * Run this only when Inter needs updating — the checked-in files are what makes
 * the PDF build reproducible and offline-capable. Inter ships as a variable
 * font, so one file per subset covers every weight.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))

const CSS_URL =
	'https://fonts.googleapis.com/css2?family=Inter:wght@100..900&subset=latin,latin-ext&display=block'

// Google serves woff2 only to browser-like clients.
const UA =
	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0 Safari/537.36'

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text()

const faces = []
for (const [, subset, block] of css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)) {
	if (subset !== 'latin' && subset !== 'latin-ext') continue

	const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)[1]
	const unicodeRange = block.match(/unicode-range:\s*([^;]+);/)[1]
	const file = `inter-${subset}.woff2`

	const bytes = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer())
	await mkdir(resolve(here, 'fonts'), { recursive: true })
	await writeFile(resolve(here, 'fonts', file), bytes)

	faces.push(`@font-face {
	font-family: 'Inter';
	font-style: normal;
	font-weight: 100 900;
	font-display: block;
	src: url('./fonts/${file}') format('woff2');
	unicode-range: ${unicodeRange};
}`)

	console.log(`${file}  ${bytes.length} B`)
}

if (faces.length !== 2) {
	console.error(`Expected latin and latin-ext, got ${faces.length} faces.`)
	process.exit(1)
}

await writeFile(
	resolve(here, 'inter.css'),
	`/*
 * Inter — latin + latin-ext, variable weight 100–900.
 * latin-ext is required for Czech diacritics and is not optional (brand guidelines §7).
 *
 * Generated by fetch-fonts.mjs. Do not edit by hand.
 */

${faces.join('\n\n')}
`,
	'utf8',
)

console.log('inter.css written')
